name: Publish SNAPSHOT
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.triggering_actor == github.repository.owner
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: 'develop'

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_SECRET }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.GPG_PASSWORD }} -P snapshot,deploy clean deploy
